# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguard-cli" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6e5f5743e1e5ac832e9fe301f363ccf52f02a5da65deae03f92281c7c0cce122"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3dc2cd857ce26cff7656d781fdd5e8b285400f1739133220d15b64c838dec971"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e4ea12a24019d3021a118b143596e8cc469b879a09b82b4341b2849c4284e85"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32e83c4508e4cc6f6a692de82e47bc000c0e8ffa235fc84c717dd43e5af2b609"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "adguard-cli"
  desc "The missing command-line interface for AdGuard Home"
  homepage "https://github.com/jjuanrivvera/adguard-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguard-home"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adguard-home"]
  end

  # No zap stanza required

end
