# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguard-cli" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "32c769033f2688bbf98e1f6034855cd67060d717647006b365c42d6a8ae4d1d0"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "90d67b04dc94e085d53901a6360d196724e2abac005f431bacee25cbc90ee37d"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c8654c29b8ef8d0a73a68329ebd005b1f19bf3f1fa04a3680d1bdc527a0fbdab"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d3f68d09bea5c39abfa29096c13fa57d002467194f82e353998cf02d3ab570f"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adguard-cli"
  desc "The missing command-line interface for AdGuard Home"
  homepage "https://github.com/jjuanrivvera/adguard-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguard-home"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adguard-home"]
  end

  # No zap stanza required
end
