# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguard-cli" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "dbfa3077fe47fb300d2dbdb7a3a85d11c8e102ee6dc53752f907a6cb722235a7"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2ef4d4d6eed354f45b95c4d2d6d0da9f1bef4861ed8badaa65763256c588d7a"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27df8837cc09f01ec3826c81255abbd53588a145d6088d966076297c45072d6c"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6f47707b13235754ede35fe7e605a93f262b2ce2293e674c8bd1913f58133de"
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v#{version}/adguard-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "adguard-cli"
  desc "The missing command-line interface for AdGuard Home"
  homepage "https://github.com/jjuanrivvera/adguard-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguard-home"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adguard-home"]
  end

  # No zap stanza required

end
