# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdguardCli < Formula
  desc "The missing command-line interface for AdGuard Home"
  homepage "https://github.com/jjuanrivvera/adguard-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.3/adguard-cli_0.2.3_darwin_amd64.tar.gz"
      sha256 "fd6d5849a766898ffccf351778f5dc3a7a9bf6bad70bb554e109beb1fe99c3be"

      define_method(:install) do
        bin.install "adguard-home"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.3/adguard-cli_0.2.3_darwin_arm64.tar.gz"
      sha256 "357376797c38031ae5998488e7a0efb01612c13308fc6e57f2ee1d2b82669a7e"

      define_method(:install) do
        bin.install "adguard-home"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.3/adguard-cli_0.2.3_linux_amd64.tar.gz"
      sha256 "71eaa24c3c95014e1368686c64ab17f56ce8777344b0a7e9d8ca0040d172dfe4"
      define_method(:install) do
        bin.install "adguard-home"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.3/adguard-cli_0.2.3_linux_arm64.tar.gz"
      sha256 "45e6f712570408a06858baa3d833fe6784690684911c7a08a9e3f03631c12988"
      define_method(:install) do
        bin.install "adguard-home"
      end
    end
  end

  test do
    system "#{bin}/adguard-home", "--version"
  end
end
