# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdguardCli < Formula
  desc "The missing command-line interface for AdGuard Home"
  homepage "https://github.com/jjuanrivvera/adguard-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.1/adguard-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "93b9231aa2f4c6058bd0991e98c36a9c497ab9c18c5e203aad6f7614ea5baeb6"

      define_method(:install) do
        bin.install "adguard-home"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.1/adguard-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "4489228e27aaf649e8849813fc86f5da8cb4088d928d943e70f71c8871dfa2fa"

      define_method(:install) do
        bin.install "adguard-home"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.1/adguard-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "b27d589558c52526ed63d7ef9e593eacd34592eeee1c81c6bec6454e074e4d19"
      define_method(:install) do
        bin.install "adguard-home"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjuanrivvera/adguard-cli/releases/download/v0.2.1/adguard-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "940d6e80e713be4668d8b71100f7877ce2a49bf3bf4b0b96ba873b752c3b71a5"
      define_method(:install) do
        bin.install "adguard-home"
      end
    end
  end

  test do
    system "#{bin}/adguard-home", "--version"
  end
end
